title: IOM # your name (or website title) here
logo: "images/5272394-company-logo-png-98-images-in-collection-page-1-company-logo-png-300_300_preview.png" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  IOM develops systems for just-in-time small parts manufacturing and fulfillment. Our technology weaves together recent methods in 3D-printing, robotic manipulation, and machine learning. 
  <br><br>
  Companies should not be forced to stock long-tail products. We enable retailers and fulfillment centers to reduce their inventory, lead time, and workforce through an all-in-one solution stack.  
  <br><br>
  <br><br>
  <br><br>
  <br><br>
  <!-- <a href="https://www.hackster.io/">View Our Hackster Profile</a> -->
  
theme: jekyll-theme-minimal
google_analytics: G-79B591TCKF  # your Google Analytics tracking ID here -- original example: UA-000000-0
